services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn TeleMarket.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: TeleMarket.settings
      - key: SECRET_KEY
        generateValue: true
