# Generated by Django 5.1.2 on 2025-05-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rating',
            table='product_rating',
        ),
    ]
